/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etla.mod.etl.form;

import etla.mod.SModConsts;
import etla.mod.etl.db.SEtlConsts;
import etla.mod.etl.db.SEtlProcess;
import java.awt.Cursor;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFormDialog;

/**
 *
 * @author Sergio Flores
 */
public class SDialogEtl extends SBeanFormDialog {

    /**
     * Creates new form SDialogEtl
     */
    public SDialogEtl(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.AX_ETL, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        moRadModeCat = new sa.lib.gui.bean.SBeanFieldRadio();
        jPanel7 = new javax.swing.JPanel();
        moRadModeCatInv = new sa.lib.gui.bean.SBeanFieldRadio();
        jPanel3 = new javax.swing.JPanel();
        jlDatePeriodStart = new javax.swing.JLabel();
        moDatePeriodStart = new sa.lib.gui.bean.SBeanFieldDate();
        jPanel4 = new javax.swing.JPanel();
        jlDatePeriodEnd = new javax.swing.JLabel();
        moDatePeriodEnd = new sa.lib.gui.bean.SBeanFieldDate();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        sBeanFieldBoolean1 = new sa.lib.gui.bean.SBeanFieldBoolean();
        jPanel10 = new javax.swing.JPanel();
        sBeanFieldRadio1 = new sa.lib.gui.bean.SBeanFieldRadio();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        sBeanFieldRadio2 = new sa.lib.gui.bean.SBeanFieldRadio();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de exportación:"));
        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgMode.add(moRadModeCat);
        moRadModeCat.setText("Exportar catálogos");
        moRadModeCat.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel6.add(moRadModeCat);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        bgMode.add(moRadModeCatInv);
        moRadModeCatInv.setText("Exportar catálogos y facturas");
        moRadModeCatInv.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel7.add(moRadModeCatInv);

        jPanel2.add(jPanel7);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatePeriodStart.setText("Fecha inicial:");
        jlDatePeriodStart.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlDatePeriodStart);
        jPanel3.add(moDatePeriodStart);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatePeriodEnd.setText("Fecha final:");
        jlDatePeriodEnd.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlDatePeriodEnd);
        jPanel4.add(moDatePeriodEnd);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio de actualización de catálogos:"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        sBeanFieldBoolean1.setText("Actualizar catálogos exportados anteriormente");
        sBeanFieldBoolean1.setEnabled(false);
        sBeanFieldBoolean1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel9.add(sBeanFieldBoolean1);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        sBeanFieldRadio1.setText("Actualizar selectivamente");
        sBeanFieldRadio1.setEnabled(false);
        sBeanFieldRadio1.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel10.add(sBeanFieldRadio1);

        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("(Últimos cambios realizados por usuarios se conservan)");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel10.add(jLabel1);

        jPanel8.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        sBeanFieldRadio2.setText("Actualizar siempre");
        sBeanFieldRadio2.setEnabled(false);
        sBeanFieldRadio2.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel11.add(sBeanFieldRadio2);

        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("(Últimos cambios realizados por usuarios se pierden)");
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel11.add(jLabel2);

        jPanel8.add(jPanel11);

        jPanel5.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlDatePeriodEnd;
    private javax.swing.JLabel jlDatePeriodStart;
    private sa.lib.gui.bean.SBeanFieldDate moDatePeriodEnd;
    private sa.lib.gui.bean.SBeanFieldDate moDatePeriodStart;
    private sa.lib.gui.bean.SBeanFieldRadio moRadModeCat;
    private sa.lib.gui.bean.SBeanFieldRadio moRadModeCatInv;
    private sa.lib.gui.bean.SBeanFieldBoolean sBeanFieldBoolean1;
    private sa.lib.gui.bean.SBeanFieldRadio sBeanFieldRadio1;
    private sa.lib.gui.bean.SBeanFieldRadio sBeanFieldRadio2;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    
    private void initComponentsCustom () {
        SGuiUtils.setWindowBounds(this, 480, 300);
        
        moRadModeCat.setBooleanSettings(SGuiUtils.getLabelName(moRadModeCat.getText()), false);
        moRadModeCatInv.setBooleanSettings(SGuiUtils.getLabelName(moRadModeCatInv.getText()), true);
        moDatePeriodStart.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatePeriodStart), true);
        moDatePeriodEnd.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatePeriodEnd), true);
        
        moFields.addField(moRadModeCat);
        moFields.addField(moRadModeCatInv);
        moFields.addField(moDatePeriodStart);
        moFields.addField(moDatePeriodEnd);
        moFields.setFormButton(jbSave);
        
        jbSave.setText(SGuiConsts.TXT_BTN_OK);
    }
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {
        
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        return validation;
    }

    @Override
    public void initForm() {
        removeAllListeners();
        reloadCatalogues();
        
        moRadModeCatInv.setValue(true);
        moDatePeriodStart.setValue(miClient.getSession().getCurrentDate());
        moDatePeriodEnd.setValue(miClient.getSession().getCurrentDate());
        //moDateIssue.setValue(...);
        
        addAllListeners();
    }
    
    @Override
    public void actionSave() {
        if (jbSave.isEnabled()) {
            if (SGuiUtils.computeValidation(miClient, validateForm())) {
                try {
                    this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                    
                    SEtlProcess.computeEtl(
                            miClient.getSession(), 
                            moRadModeCat.isSelected() ? SEtlConsts.ETL_MODE_CAT : SEtlConsts.ETL_MODE_CAT_INV, 
                            moDatePeriodStart.getValue(), 
                            moDatePeriodEnd.getValue(), 
                            miClient.getSession().getSystemDate(), 
                            sBeanFieldBoolean1.getValue());
                    
                    miClient.showMsgBoxInformation(SLibConsts.MSG_PROCESS_FINISHED);
                    
                    mnFormResult = SGuiConsts.FORM_RESULT_OK;
                    dispose();
                }
                catch (Exception e) {
                    SLibUtils.showException(this, e);
                }
                finally {
                    this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                }
            }
        }
    }
}
